# Generated by Django 6.0.5 on 2026-06-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_customers_a_key_pre_idx_customers_a_key_pre_0b7f88_idx'),
        ('invoices', '0002_auditlog_invoicelineitem_remove_invoice_amount_cents_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('customer', 'period_start', 'period_end')},
        ),
    ]
