# Generated by Django 6.0.5 on 2026-06-04 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_customers_a_key_pre_idx_customers_a_key_pre_0b7f88_idx'),
        ('usage', '0002_usagewindow_and_update_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usageevent',
            new_name='usage_usage_custome_6ac45c_idx',
            old_name='usage_event_cust_ts',
        ),
        migrations.RenameIndex(
            model_name='usageevent',
            new_name='usage_usage_custome_dc19f2_idx',
            old_name='usage_event_cust_ts_desc',
        ),
        migrations.RenameIndex(
            model_name='usagewindow',
            new_name='usage_usage_custome_22d760_idx',
            old_name='usage_window_cust_ws',
        ),
        migrations.RenameIndex(
            model_name='usagewindow',
            new_name='usage_usage_is_invo_02a29d_idx',
            old_name='usage_window_invoiced',
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='request_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
