# Generated by Django 6.0.5 on 2026-06-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_apikey'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apikey',
            new_name='customers_a_key_pre_0b7f88_idx',
            old_name='customers_a_key_pre_idx',
        ),
    ]
