# Generated by Django 6.0.5 on 2026-06-01 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='amount_cents',
        ),
        migrations.AddField(
            model_name='credit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='customers.customer'),
        ),
    ]
