# Generated by Django 6.0.5 on 2026-06-04 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_credit_update'),
        ('ops', '0002_remove_credit_amount_cents_credit_amount_and_more'),
    ]

    operations = [
    ]
