# Generated by Django 6.0.5 on 2026-06-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_merge_20260603_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='amount_cents',
            field=models.BigIntegerField(),
        ),
    ]
